language: bash
dist: xenial
group: edge
sudo: required
cache:
  directories:
  - "${HOME}/bin"
  - "${HOME}/.cache/travis-terraform-config"
env:
  global:
  - PATH="${HOME}/bin:${PATH}"
  - TMPDIR="${TMPDIR:-/tmp}"
before_install:
- rvm use --install --fuzzy "$(cat .ruby-version)"
- eval "$(gimme 1.11.1)"
- make deps
script:
- make test
- make assert-clean
